// Run a local server first. Set PLAYWRIGHT_MODULE if Playwright is installed outside this repo.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const root = path.resolve(__dirname, '..');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const requests = []; page.on('request', r => requests.push(r.url()));
  await page.goto(process.env.DEMO_URL || 'http://127.0.0.1:5082/');
  await page.locator('#full-name').waitFor({ state: 'visible' });
  const original = await page.locator('#full-name').textContent(); assert(original.length > 8);
  assert.match(await page.locator('.demo-note').textContent(), /datos ficticios/);
  await page.locator('#dni').fill('１２３４５６７８'); await page.locator('#lookup button').click();
  assert.match(await page.locator('#lookup-error').textContent(), /8 dígitos/);
  await page.locator('#dni').fill('00123456'); await page.locator('#lookup button').click();
  assert.equal(await page.locator('#card-dni').textContent(), '00123456');
  const fullName = await page.locator('#full-name').textContent();
  await page.locator('#compare-name').fill(fullName); await page.locator('#compare').click();
  assert.match(await page.locator('#comparison').textContent(), /^Coincide/);
  await page.locator('#compare-name').fill(fullName.split(' ')[0] + ' Apellido Erróneo'); await page.locator('#compare').click();
  assert.match(await page.locator('#comparison').textContent(), /difiere/);
  const jsonDownload = page.waitForEvent('download'); await page.locator('#download-profile').click(); const json = await jsonDownload;
  assert.equal(JSON.parse(fs.readFileSync(await json.path(), 'utf8')).dni, '00123456');
  await page.locator('#single-tab').focus(); await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#batch-tab').getAttribute('aria-selected'), 'true');
  await page.locator('#sample').click(); assert.equal(await page.locator('#results-body tr').count(), 5);
  assert.match(await page.locator('#summary').textContent(), /1 repetidos/);
  const csvDownload = page.waitForEvent('download'); await page.locator('#export').click(); const csv = await csvDownload;
  assert.match(fs.readFileSync(await csv.path(), 'utf8'), /Datos ficticios; no verifica identidad/);
  await page.locator('#batch-text').fill('Documento;Nombre completo\n00123456;"<img src=x onerror=alert(1)>"\n12345678;@SUM(1,1)');
  await page.locator('#use-paste').click(); await page.locator('#process').click();
  assert.equal(await page.locator('#results-body img').count(), 0); assert.match(await page.locator('#results-body').textContent(), /<img/);
  await page.locator('#name-column').selectOption('0'); await page.locator('#process').click();
  assert.match(await page.locator('#batch-error').textContent(), /columnas diferentes/);
  await page.locator('#file').setInputFiles(path.join(root, 'examples/registros.xlsx'));
  await page.waitForFunction(() => !document.getElementById('mapping').hidden && document.getElementById('sheet').options.length === 2);
  await page.locator('#process').click(); assert.equal(await page.locator('#results-body tr').count(), 3);
  assert.equal(await page.locator('#results-body tr').first().locator('td').first().locator('strong').textContent(), '00123456');
  await page.locator('#sheet').selectOption('1'); await page.locator('#process').click(); assert.equal(await page.locator('#results-body tr').count(), 2);
  await page.locator('#file').setInputFiles({ name: 'broken.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.from('broken') });
  await page.waitForFunction(() => document.getElementById('batch-error').textContent.includes('XLSX'));
  assert.equal(await page.locator('#mapping').isVisible(), false);
  await page.locator('#batch-text').fill('DNI\n"bad'); await page.locator('#use-paste').click(); assert.match(await page.locator('#batch-error').textContent(), /comillas/);
  await page.locator('#single-tab').click();
  await page.locator('#dni').fill('12345678'); await page.locator('#lookup button').click(); await page.locator('#compare-name').fill('');
  await page.evaluate(() => document.activeElement.blur());
  await page.screenshot({ path: path.join(root, 'assets/screenshots/desktop.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 1000, height: 750 }); await page.screenshot({ path: path.join(root, 'assets/screenshots/portfolio-1000x750.png'), animations: 'disabled' });
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.locator('#batch-tab').click(); await page.locator('#sample').click();
  await page.evaluate(() => document.activeElement.blur());
  await page.screenshot({ path: path.join(root, 'assets/screenshots/batch.png'), fullPage: true, animations: 'disabled' });
  for (const width of [360, 390, 768, 1000, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `horizontal overflow: ${width}`);
  }
  await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#single-tab').click();
  await page.evaluate(() => document.activeElement.blur());
  await page.screenshot({ path: path.join(root, 'assets/screenshots/mobile.png'), fullPage: true, animations: 'disabled' });
  assert.deepEqual(errors, []); assert(requests.every(url => url.startsWith('http://127.0.0.1:5082/')), 'Unexpected remote request');
  await browser.close(); console.log('PASS: single, errors, full-name comparison, tabs keyboard, JSON download, batch, duplicate, CSV download, XSS, mapping, two-sheet XLSX, malformed imports, responsive 360/390/768/1000/1440, zero page errors and remote requests.');
})().catch(e => { console.error(e); process.exit(1); });
